import type { NextPage } from 'next'
import Head from 'next/head'
import LoginForm from '../components/login-form'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Balls</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="vh-100 d-flex justify-content-center align-items-center">
        <LoginForm/>
      </main>
    </div>
  )
}

export default Home