-- Nuke everything
DROP TABLE IF EXISTS Offer CASCADE;

DROP TABLE IF EXISTS Voucher_Order CASCADE;

DROP TABLE IF EXISTS Ordine CASCADE;

DROP TABLE IF EXISTS Voucher CASCADE;

DROP TABLE IF EXISTS Seeker CASCADE;

DROP TABLE IF EXISTS Supplier CASCADE;

DROP TABLE IF EXISTS Billing CASCADE;

DROP TABLE IF EXISTS Address CASCADE;

DROP TABLE IF EXISTS Category CASCADE;